---
# tasks file for deploy_nginx_config_and_letsencrypt_cert
- name: Copy Nginx Config
  copy: src=nginx.conf dest=/etc/nginx mode=0555
  notify: Restart Nginx

- name: Copy Nginx Upstream Servers
  copy: src=upstream.conf dest=/etc/nginx/conf.d mode=0555
  notify: Restart Nginx